project_id = "yudnrvzjeqtyldrpbunw"

[functions.gmail]
verify_jwt = true

[functions.verify-bank]
verify_jwt = true

[functions.process-transactions]
verify_jwt = true

[functions.refresh-google-token]
verify_jwt = true

[functions.gmail-webhook]
verify_jwt = false

[functions.process-email-notifications]
verify_jwt = true

[functions.background-transaction-processor]
verify_jwt = false

[functions.email-monitor-health-check]
verify_jwt = false

[functions.debug-user-auth]
verify_jwt = true