// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yudnrvzjeqtyldrpbunw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1ZG5ydnpqZXF0eWxkcnBidW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjQ2ODksImV4cCI6MjA3Mzk0MDY4OX0.FZyYwsMpKPhUSmW2MWlFaPN42NmdnSgHAjhG_VKJlpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});